//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miniblog.Core.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Miniblog.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BadRequestTheRequestCannotBeFulfilledDueToBadSyntax {
            get {
                return ResourceManager.GetString("BadRequestTheRequestCannotBeFulfilledDueToBadSyntax", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        public static string InternalServerErrorServerWasUnableToFinishProcessingTheRequest {
            get {
                return ResourceManager.GetString("InternalServerErrorServerWasUnableToFinishProcessingTheRequest", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string MiniblogCore {
            get {
                return ResourceManager.GetString("MiniblogCore", resourceCulture);
            }
        }
        
        public static string NewPost {
            get {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }
        
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string SignInAsAdministrator {
            get {
                return ResourceManager.GetString("SignInAsAdministrator", resourceCulture);
            }
        }
        
        public static string SignInToTheWebsite {
            get {
                return ResourceManager.GetString("SignInToTheWebsite", resourceCulture);
            }
        }
        
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        public static string SignOutAsAdministrator {
            get {
                return ResourceManager.GetString("SignOutAsAdministrator", resourceCulture);
            }
        }
        
        public static string SomeFeaturesOfThisWebsiteDoNotWorkAsExpectedWhenJavaScriptIsDisabled {
            get {
                return ResourceManager.GetString("SomeFeaturesOfThisWebsiteDoNotWorkAsExpectedWhenJavaScriptIsDisabled", resourceCulture);
            }
        }
        
        public static string ThatsOddSomethingWeDidntExpectHappened {
            get {
                return ResourceManager.GetString("ThatsOddSomethingWeDidntExpectHappened", resourceCulture);
            }
        }
        
        public static string ThePageYouRequestedCanNotBeShownBecauseYouAreOffline {
            get {
                return ResourceManager.GetString("ThePageYouRequestedCanNotBeShownBecauseYouAreOffline", resourceCulture);
            }
        }
        
        public static string TheServerTimedOutWaitingForTheRequest {
            get {
                return ResourceManager.GetString("TheServerTimedOutWaitingForTheRequest", resourceCulture);
            }
        }
        
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        public static string UsernameOrPasswordIsInvalid {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsInvalid", resourceCulture);
            }
        }
    }
}
